### ISSUE TITLE
Time-scaling missing in Bachelier formula

### ISSUE THREAD

**Issue by bmyksvoll** [ArnaudBu/esg2#2]
I think there is a missing factor in the Swaptions-class.R file, line nr 69

p[i] <- volSwap * (dnorm(d)) * payments 

I believe it should be:

p[i] <- volSwap * (dnorm(d)) * payments * sqrt(matSwap)

**Comment by ArnaudBu** [comment]
Hi @bmyksvoll,

Thanks a lot for noticing this!

I have corrected the mistake in commit [d4f012e](https://github.com/ArnaudBu/esg2/commit/d4f012e53bddaf93ddc20392e0bc9dff5e93bfeb).

Have a great day!
